name: np_platform_local_media
description: "A new Flutter plugin project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  np_common:
    path: ../np_common
  np_datetime:
    path: ../np_datetime
  np_platform_util:
    path: ../np_platform_util
  plugin_platform_interface: ^2.0.2
  to_string:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string-2.0.0
      path: to_string

dev_dependencies:
  build_runner: ^2.4.9
  dart_style: 3.0.1
  np_lints:
    path: ../np_lints
  pigeon: ^22.6.0
  to_string_build:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string_build-2.0.0
      path: to_string_build

flutter:
  plugin:
    platforms:
      android:
        package: com.nkming.nc_photos.np_platform_local_media
        pluginClass: NpPlatformLocalMediaPlugin
