name: np_gps_map
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_map_marker_cluster: ^8.2.2
  google_maps_flutter: 2.5.3
  google_maps_cluster_manager:
    git:
      url: https://github.com/bpillon/google_maps_cluster_manager.git
      ref: 7ab2a6363f70cbc775a84fb09a0abcf0d546cdae
  latlong2: any
  np_async:
    path: ../np_async
  np_collection:
    path: ../np_collection
  np_common:
    path: ../np_common
  np_platform_util:
    path: ../np_platform_util
  rxdart: ^0.27.7

dev_dependencies:
  dart_style: 3.0.1
  np_lints:
    path: ../np_lints

flutter:
  plugin:
    platforms:
      android:
        package: com.nkming.nc_photos.np_gps_map
        pluginClass: NpGpsMapPlugin
  assets:
    - assets/
